import PostProvider from "@/context/PostProvider";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
const RootLayout = ({ children }) => {
	return (
		<html>
			<body>
				<main>
					<PostProvider>{children}</PostProvider>
				</main>
			</body>
		</html>
	);
};

export default RootLayout;
